version: 2.1

orbs:
  python: circleci/python@2.0.3
  ship: auth0/ship@0.5.0
  codecov: codecov/codecov@3

jobs:
  build_and_test:
    parameters:
      py_version:
        type: string
        default: "3.10"
    docker:
      - image: cimg/python:<< parameters.py_version >>
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - when:
          condition:
            not:
              equal: ["3.7", << parameters.py_version >> ]
          steps:
            - run: pre-commit run --all-files
      - run: coverage run -m unittest
      - run: bash <(curl -s https://codecov.io/bash)
      - when:
          condition:
            equal: [ "3.10", << parameters.py_version >> ]
          steps:
            - run: make -C docs html

workflows:
  main:
    jobs:
      - build_and_test:
          matrix:
            parameters:
              py_version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]
      - ship/python-publish:
          prefix-tag: false
          context:
            - publish-pypi
            - publish-gh
          filters:
            branches:
              only:
                - master
          requires:
            - build_and_test
